### ISSUE TITLE
I found this interesting and would like to deploy it on my own computer

### ISSUE THREAD

**Issue by bill-ysn** [Elenadisa/PhenCo#3]
Hi Elenadisa:
    I found this interesting and would like to deploy it on my own computer.
    If I want to reproduce it, I just have to follow the readme document, right?

**Comment by Elenadisa** [comment]
Hi bill-ysn! You can run the workflow following the instructions of the readme document.

**Comment by bill-ysn** [comment]
@Elenadisa 好的，非常感谢！
