### ISSUE TITLE
Thank you very much for updating  codes and instructions! Where can I find the test input file?

### ISSUE THREAD

**Issue by marklwzbupt** [Elenadisa/PhenCo#4]
Hi Elenadisa!
I really appreciate your help! Where could  I find the test input file(test_input.txt) ?

**Comment by Elenadisa** [comment]
Hi lwz0324!
test_input.txt is in external_data directory. I've just updated some lines of the workflow to include the path of the file. Please update the clone repository to get the new version.

**Comment by marklwzbupt** [comment]
Thanks for updating! I'll try it.
