### ISSUE TITLE
Unable to find temp folder or file, temp has other meaning?

### ISSUE THREAD

**Issue by bill-ysn** [Elenadisa/PhenCo#6]
Dear Elenadisa:
         Executing 'lauch_build_networks.sh' reported an error that could not open temp, and seeing this in 'lauch_build_networks.sh' got me wondering.
         hope you can clear this up for me. Thank you.
![A(M9ZT 0W`6BQY@ZQ L_QWM](https://user-images.githubusercontent.com/70495121/108950072-8ef1fa80-76a0-11eb-89b6-8f7a3f8fa62b.png)

**Comment by Elenadisa** [comment]
Thanks for your question. The problem is already solved. With the update the script should work by now, so please update it

**Comment by bill-ysn** [comment]
@Elenadisa Thank you very much for your answer.
Give you a small suggestion, the latter two 'sh' files have some path problems, for the user is not easy to check, if the comments are more detailed to use more smooth.

I found a fixed PATH is wrong in one of the md files of the third script, and I changed the fixed PATH in the previous PATH. May I ask whether I should keep the same with you or do other operations?

Thank you again for your answer!


![1614242732](https://user-images.githubusercontent.com/70495121/109127053-f08d9400-7788-11eb-8d92-b6b4bf204f5e.png)
error: pandoc document conversion failed with error 67

**Comment by bill-ysn** [comment]
@Elenadisa Sorry to bother you again.For the above problem, I tried to change to my path, but the data cannot be transferred into the situation.However, it is feasible for me to manually input the code with R. I really don't know how to modify it. Maybe I made some mistake or something before.Also ask the author you give me directions.Thank you very much. run 'get_comparative_results.sh' The error screenshot is as follows(There are a few others that are similar to the document that I didn't put up):
![1](https://user-images.githubusercontent.com/70495121/109238692-f7f78080-780e-11eb-8123-6f632ad89b27.png)
![2](https://user-images.githubusercontent.com/70495121/109238696-fa59da80-780e-11eb-9e91-d806c16dfe8a.png)
![4](https://user-images.githubusercontent.com/70495121/109238698-fcbc3480-780e-11eb-914b-071100a02f4a.png)
![6](https://user-images.githubusercontent.com/70495121/109238705-ffb72500-780e-11eb-8dcc-8df536f4c0bd.png)

Looking forward to your reply. Thank you very much!

**Comment by Elenadisa** [comment]
Thanks for your interest and well-described, informative message.
We are working in your comments. I'll get back to you when we it's fixed.
Kindest regards
Elena

**Comment by bill-ysn** [comment]
That's great. I'm looking forward to your restoration.

**Comment by bill-ysn** [comment]
That's great. I'm looking forward to your restoration.

**Comment by Elenadisa** [comment]
@bill-ysn thank you for your comments. Path problems you reported have been fixed fixed. But with the test file only the first two parts of the workflow can be executed. Reports cannot be generated. This test file is just an example of how the input format of the data set should look like

**Comment by bill-ysn** [comment]
@Elenadisa Great! Thank you very much for taking my advice!
Then I need to prepare complete data to run the whole process and get the generated report, right?
I'm sorry to bother you again.

**Comment by Elenadisa** [comment]
@bill-ysn You have to use your own patient cohort or DECIPHER dataset
